package com.fleetrental.view.mainjframe;

import com.fleetrental.model.domain.Itinerary;

/**
 * ItineraryJFrame.java
 *
 * Build one of the GUIs (View) for the FleetRental application.
 *
 * Note:
 * 
 * This class doesn't implement all the View classes
 * in its entirety. This is just a sample implementation. 
 * 
 * For example, customer's are allowed to enter their
 * itinerary but no view is built for viewing the available cars, choosing
 * the rental and making payments.
 *
 *
 * @author  Mike.Prasad
 */
public class MainJFrame extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 3320197207777135961L;
	
	/** Creates new form ItineraryJFrame */
    public MainJFrame() {
        initComponents();
        
        this.setSize(350,300);                
        this.setVisible(true); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jMenuBar = new javax.swing.JMenuBar();
  setJMenuBar(jMenuBar);
  jFileMenu = new javax.swing.JMenu();
  jDataMenu = new javax.swing.JMenu();
  jFileMenuItem = new javax.swing.JMenuItem();
  jDatabaseMenuItem = new javax.swing.JMenuItem();
  jPanel1 = new javax.swing.JPanel();
  jLabelPickUpCity = new javax.swing.JLabel();
  jTextFieldPickUpCity = new javax.swing.JTextField();
  jLabelDropOffCity = new javax.swing.JLabel();
  jTextFieldDropOffCity = new javax.swing.JTextField();
  jButtonGetAvailableRentals = new javax.swing.JButton();
  jLabelPickUpDate = new javax.swing.JLabel();
  jTextFieldPickUpDateMonth = new javax.swing.JTextField();
  jLabelPickUpDateMonth = new javax.swing.JLabel();
  jLabelPickUpDateDay = new javax.swing.JLabel();
  jTextFieldPickUpDateDay = new javax.swing.JTextField();
  jLabelPickUpDateYear = new javax.swing.JLabel();
  jTextFieldPickUpDateYear = new javax.swing.JTextField();
  jLabelDropOffDate = new javax.swing.JLabel();
  jLabelDropOffDateMonth = new javax.swing.JLabel();
  jTextFieldDropOffDateMonth = new javax.swing.JTextField();
  jLabelDropOffDateDay = new javax.swing.JLabel();
  jTextFieldDropOffDateDay = new javax.swing.JTextField();
  jLabelDropOffDateYear = new javax.swing.JLabel();
  jTextFieldDropOffDateYear = new javax.swing.JTextField();
  jLabelPickUpDateTime = new javax.swing.JLabel();
  jTextFieldPickUpDateTime = new javax.swing.JTextField();
  jLabelDropOffDateTime = new javax.swing.JLabel();
  jTextFieldDropOffDateTime = new javax.swing.JTextField();
  jButtonRegisterCustomer = new javax.swing.JButton();

  jMenuBar.setNextFocusableComponent(jFileMenu);
  jMenuBar.setOpaque(false);

  jFileMenu.setText("File");
  jFileMenu.setFont(new java.awt.Font("Comic Sans MS", 1, 11));

  jDataMenu.setText("Data");
  jDataMenu.setFont(new java.awt.Font("Comic Sans MS", 1, 11));

  jFileMenuItem.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jFileMenuItem.setText("Open From File...");
  jDataMenu.add(jFileMenuItem);

  jDatabaseMenuItem.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jDatabaseMenuItem.setText("Open from database...");
  jDatabaseMenuItem.setActionCommand("Open from Database...");
  jDataMenu.add(jDatabaseMenuItem);

  jFileMenu.add(jDataMenu);

  jMenuBar.add(jFileMenu);

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  setTitle("Fleet Rental");
  setFont(new java.awt.Font("Comic Sans MS", 0, 10));
  getContentPane().setLayout(null);

  jPanel1.setBackground(new java.awt.Color(153, 153, 255));
  jPanel1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
  jPanel1.setLayout(null);

  jLabelPickUpCity.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelPickUpCity.setText("PickUp City:");
  jPanel1.add(jLabelPickUpCity);
  jLabelPickUpCity.setBounds(47, 10, 70, 17);

  jTextFieldPickUpCity.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
  jTextFieldPickUpCity.setText("San Francisco");
  jPanel1.add(jTextFieldPickUpCity);
  jTextFieldPickUpCity.setBounds(130, 10, 90, 22);

  jLabelDropOffCity.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelDropOffCity.setText("Drop Off City:");
  jPanel1.add(jLabelDropOffCity);
  jLabelDropOffCity.setBounds(17, 30, 100, 17);

  jTextFieldDropOffCity.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
  jTextFieldDropOffCity.setText("San Francisco");
  jPanel1.add(jTextFieldDropOffCity);
  jTextFieldDropOffCity.setBounds(130, 30, 90, 22);

  jButtonGetAvailableRentals.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
  jButtonGetAvailableRentals.setLabel("Get Available Rentals");
  jButtonGetAvailableRentals.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButtonGetAvailableRentalsActionPerformed(evt);
   }
  });
  jPanel1.add(jButtonGetAvailableRentals);
  jButtonGetAvailableRentals.setBounds(20, 200, 150, 25);

  jLabelPickUpDate.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelPickUpDate.setText("PickUp Date:");
  jPanel1.add(jLabelPickUpDate);
  jLabelPickUpDate.setBounds(20, 60, 80, 17);

  jTextFieldPickUpDateMonth.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
  jTextFieldPickUpDateMonth.setText("05");
  jPanel1.add(jTextFieldPickUpDateMonth);
  jTextFieldPickUpDateMonth.setBounds(150, 60, 20, 20);

  jLabelPickUpDateMonth.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelPickUpDateMonth.setText("MM:");
  jPanel1.add(jLabelPickUpDateMonth);
  jLabelPickUpDateMonth.setBounds(110, 60, 30, 17);

  jLabelPickUpDateDay.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelPickUpDateDay.setText("DD:");
  jPanel1.add(jLabelPickUpDateDay);
  jLabelPickUpDateDay.setBounds(180, 60, 30, 17);

  jTextFieldPickUpDateDay.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
  jTextFieldPickUpDateDay.setText("05");
  jPanel1.add(jTextFieldPickUpDateDay);
  jTextFieldPickUpDateDay.setBounds(210, 60, 20, 20);

  jLabelPickUpDateYear.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelPickUpDateYear.setText("YYYY: ");
  jPanel1.add(jLabelPickUpDateYear);
  jLabelPickUpDateYear.setBounds(250, 60, 40, 17);

  jTextFieldPickUpDateYear.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
  jTextFieldPickUpDateYear.setText("2005");
  jPanel1.add(jTextFieldPickUpDateYear);
  jTextFieldPickUpDateYear.setBounds(290, 60, 50, 20);

  jLabelDropOffDate.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelDropOffDate.setText("Drop Off Date:");
  jPanel1.add(jLabelDropOffDate);
  jLabelDropOffDate.setBounds(10, 90, 90, 17);

  jLabelDropOffDateMonth.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelDropOffDateMonth.setText("MM:");
  jPanel1.add(jLabelDropOffDateMonth);
  jLabelDropOffDateMonth.setBounds(110, 90, 30, 17);

  jTextFieldDropOffDateMonth.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
  jTextFieldDropOffDateMonth.setText("05");
  jPanel1.add(jTextFieldDropOffDateMonth);
  jTextFieldDropOffDateMonth.setBounds(150, 90, 20, 20);

  jLabelDropOffDateDay.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelDropOffDateDay.setText("DD:");
  jPanel1.add(jLabelDropOffDateDay);
  jLabelDropOffDateDay.setBounds(180, 90, 30, 17);

  jTextFieldDropOffDateDay.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
  jTextFieldDropOffDateDay.setText("05");
  jPanel1.add(jTextFieldDropOffDateDay);
  jTextFieldDropOffDateDay.setBounds(210, 90, 20, 20);

  jLabelDropOffDateYear.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelDropOffDateYear.setText("YYYY: ");
  jPanel1.add(jLabelDropOffDateYear);
  jLabelDropOffDateYear.setBounds(250, 90, 40, 17);

  jTextFieldDropOffDateYear.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
  jTextFieldDropOffDateYear.setText("2005");
  jPanel1.add(jTextFieldDropOffDateYear);
  jTextFieldDropOffDateYear.setBounds(290, 90, 50, 20);

  jLabelPickUpDateTime.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelPickUpDateTime.setText("Time:");
  jPanel1.add(jLabelPickUpDateTime);
  jLabelPickUpDateTime.setBounds(350, 60, 40, 17);

  jTextFieldPickUpDateTime.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
  jTextFieldPickUpDateTime.setText("12:00");
  jPanel1.add(jTextFieldPickUpDateTime);
  jTextFieldPickUpDateTime.setBounds(390, 60, 50, 20);

  jLabelDropOffDateTime.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jLabelDropOffDateTime.setText("Time:");
  jPanel1.add(jLabelDropOffDateTime);
  jLabelDropOffDateTime.setBounds(350, 90, 40, 17);

  jTextFieldDropOffDateTime.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
  jTextFieldDropOffDateTime.setText("1:00");
  jPanel1.add(jTextFieldDropOffDateTime);
  jTextFieldDropOffDateTime.setBounds(390, 90, 50, 20);

  jButtonRegisterCustomer.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
  jButtonRegisterCustomer.setText("Register Customer");
  jPanel1.add(jButtonRegisterCustomer);
  jButtonRegisterCustomer.setBounds(180, 200, 150, 25);

  getContentPane().add(jPanel1);
  jPanel1.setBounds(0, 0, 450, 300);

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void jButtonGetAvailableRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetAvailableRentalsActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_jButtonGetAvailableRentalsActionPerformed

    /**
     * Returns jFileMenuItem 
     */
    public javax.swing.JMenuItem getFileMenuItem()
    {
        return jFileMenuItem;
    }


    /**
     * Returns jDatabaseMenuItem 
     */
    public javax.swing.JMenuItem getDatabaseMenuItem()
    {
        return jDatabaseMenuItem;
    }    

    /**
     * Returns jButtonGetAvailableRentals 
     */    
    public javax.swing.JButton getGetAvailableRentalsButton()
    {
        return jButtonGetAvailableRentals;
    }    

        /**
     * Returns jButtonGetAvailableRentals
     */
    public javax.swing.JButton getGetRegisterCustomerButton()
    {
        return jButtonRegisterCustomer;
    }

    /**
     * Returns an Itinerary domain object populated with user entered
     * data.
     */
    public Itinerary getSelectedData()
    {
        
        Itinerary itinerary = new Itinerary (jTextFieldPickUpCity.getText(),
                                             jTextFieldDropOffCity.getText(), 
                                             jTextFieldPickUpDateMonth.getText(), 
                                             jTextFieldPickUpDateDay.getText(),
                                             jTextFieldPickUpDateYear.getText(),
                                             jTextFieldPickUpDateTime.getText(),
                                             jTextFieldDropOffDateMonth.getText(), 
                                             jTextFieldDropOffDateDay.getText(),
                                             jTextFieldDropOffDateYear.getText(),
                                             jTextFieldDropOffDateTime.getText()
                                           );
        return itinerary;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainJFrame itineraryJFrame = new MainJFrame();
                //itineraryJFrame.setSize(350,300);
                
                //itineraryJFrame.setVisible(true);                
                
                //new ItineraryJFrame().setVisible(true);
            }
        });
    }
    
 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton jButtonGetAvailableRentals;
 private javax.swing.JButton jButtonRegisterCustomer;
 private javax.swing.JMenu jDataMenu;
 private javax.swing.JMenuItem jDatabaseMenuItem;
 private javax.swing.JMenu jFileMenu;
 private javax.swing.JMenuItem jFileMenuItem;
 private javax.swing.JLabel jLabelDropOffCity;
 private javax.swing.JLabel jLabelDropOffDate;
 private javax.swing.JLabel jLabelDropOffDateDay;
 private javax.swing.JLabel jLabelDropOffDateMonth;
 private javax.swing.JLabel jLabelDropOffDateTime;
 private javax.swing.JLabel jLabelDropOffDateYear;
 private javax.swing.JLabel jLabelPickUpCity;
 private javax.swing.JLabel jLabelPickUpDate;
 private javax.swing.JLabel jLabelPickUpDateDay;
 private javax.swing.JLabel jLabelPickUpDateMonth;
 private javax.swing.JLabel jLabelPickUpDateTime;
 private javax.swing.JLabel jLabelPickUpDateYear;
 private javax.swing.JMenuBar jMenuBar;
 private javax.swing.JPanel jPanel1;
 private javax.swing.JTextField jTextFieldDropOffCity;
 private javax.swing.JTextField jTextFieldDropOffDateDay;
 private javax.swing.JTextField jTextFieldDropOffDateMonth;
 private javax.swing.JTextField jTextFieldDropOffDateTime;
 private javax.swing.JTextField jTextFieldDropOffDateYear;
 private javax.swing.JTextField jTextFieldPickUpCity;
 private javax.swing.JTextField jTextFieldPickUpDateDay;
 private javax.swing.JTextField jTextFieldPickUpDateMonth;
 private javax.swing.JTextField jTextFieldPickUpDateTime;
 private javax.swing.JTextField jTextFieldPickUpDateYear;
 // End of variables declaration//GEN-END:variables
    
}
