package com.fleetrental.view.registercustomerjframe;

import com.fleetrental.model.domain.Customer;

/**
 * RegisterCustomerJFrame.java
 *
 * UI to capture customer registration information.
 *
 * @author  Mike.Prasad
 */
public class RegisterCustomerJFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = -685641941903021280L;
	
	private RegisterCustomerJFrameController registerCustomerJFrameController;

    /** Creates new form ItineraryJFrame */
    public RegisterCustomerJFrame() {
        initComponents();

        registerCustomerJFrameController = new RegisterCustomerJFrameController(this);

        this.setSize(350,300);                
        this.setVisible(true); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jMenuBar = new javax.swing.JMenuBar();
  setJMenuBar(jMenuBar);
  jFileMenu = new javax.swing.JMenu();
  jDataMenu = new javax.swing.JMenu();
  jFileMenuItem = new javax.swing.JMenuItem();
  jDatabaseMenuItem = new javax.swing.JMenuItem();
  jPanel1 = new javax.swing.JPanel();
  jLabelPickUpCity = new javax.swing.JLabel();
  jTextFieldFirstName = new javax.swing.JTextField();
  jLabelDropOffCity = new javax.swing.JLabel();
  jTextFieldLastName = new javax.swing.JTextField();
  jButtonCancel = new javax.swing.JButton();
  jLabelPickUpDate = new javax.swing.JLabel();
  jTextFieldEmail = new javax.swing.JTextField();
  jLabelPickUpDateDay = new javax.swing.JLabel();
  jTextFieldEveningPhone = new javax.swing.JTextField();
  jLabelDropOffDate = new javax.swing.JLabel();
  jTextFieldPassword = new javax.swing.JTextField();
  jLabelDropOffDateDay = new javax.swing.JLabel();
  jTextFieldDayPhone = new javax.swing.JTextField();
  jButtonOk = new javax.swing.JButton();

  jMenuBar.setNextFocusableComponent(jFileMenu);
  jMenuBar.setOpaque(false);

  jFileMenu.setText("File");
  jFileMenu.setFont(new java.awt.Font("Comic Sans MS", 1, 11));

  jDataMenu.setText("Data");
  jDataMenu.setFont(new java.awt.Font("Comic Sans MS", 1, 11));

  jFileMenuItem.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jFileMenuItem.setText("Open From File...");
  jDataMenu.add(jFileMenuItem);

  jDatabaseMenuItem.setFont(new java.awt.Font("Comic Sans MS", 1, 11));
  jDatabaseMenuItem.setText("Open from database...");
  jDatabaseMenuItem.setActionCommand("Open from Database...");
  jDataMenu.add(jDatabaseMenuItem);

  jFileMenu.add(jDataMenu);

  jMenuBar.add(jFileMenu);

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  setTitle("Fleet Rental Itinerary");
  setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
  getContentPane().setLayout(null);

  jPanel1.setBackground(new java.awt.Color(153, 153, 255));
  jPanel1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
  jPanel1.setLayout(null);

  jLabelPickUpCity.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
  jLabelPickUpCity.setText("First Name:");
  jPanel1.add(jLabelPickUpCity);
  jLabelPickUpCity.setBounds(40, 20, 70, 17);

  jTextFieldFirstName.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
  jTextFieldFirstName.setText("Homer");
  jPanel1.add(jTextFieldFirstName);
  jTextFieldFirstName.setBounds(130, 20, 120, 22);

  jLabelDropOffCity.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
  jLabelDropOffCity.setText("Last Name :");
  jPanel1.add(jLabelDropOffCity);
  jLabelDropOffCity.setBounds(40, 50, 70, 17);

  jTextFieldLastName.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
  jTextFieldLastName.setText("Simpson");
  jPanel1.add(jTextFieldLastName);
  jTextFieldLastName.setBounds(130, 50, 120, 22);

  jButtonCancel.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
  jButtonCancel.setText("Cancel");
  jPanel1.add(jButtonCancel);
  jButtonCancel.setBounds(190, 230, 80, 25);

  jLabelPickUpDate.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
  jLabelPickUpDate.setText("Email : ");
  jPanel1.add(jLabelPickUpDate);
  jLabelPickUpDate.setBounds(70, 80, 80, 17);

  jTextFieldEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
  jTextFieldEmail.setText("homer@duff.com");
  jPanel1.add(jTextFieldEmail);
  jTextFieldEmail.setBounds(130, 80, 120, 20);

  jLabelPickUpDateDay.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
  jLabelPickUpDateDay.setText("Day Phone : ");
  jPanel1.add(jLabelPickUpDateDay);
  jLabelPickUpDateDay.setBounds(40, 140, 70, 17);

  jTextFieldEveningPhone.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
  jTextFieldEveningPhone.setText("888.888.8888");
  jPanel1.add(jTextFieldEveningPhone);
  jTextFieldEveningPhone.setBounds(130, 170, 120, 20);

  jLabelDropOffDate.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
  jLabelDropOffDate.setText("Password : ");
  jPanel1.add(jLabelDropOffDate);
  jLabelDropOffDate.setBounds(50, 110, 90, 17);

  jTextFieldPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
  jTextFieldPassword.setText("duff");
  jPanel1.add(jTextFieldPassword);
  jTextFieldPassword.setBounds(130, 110, 120, 20);

  jLabelDropOffDateDay.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
  jLabelDropOffDateDay.setText("Evening Phone : ");
  jPanel1.add(jLabelDropOffDateDay);
  jLabelDropOffDateDay.setBounds(20, 170, 100, 17);

  jTextFieldDayPhone.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
  jTextFieldDayPhone.setText("777.777.7777");
  jPanel1.add(jTextFieldDayPhone);
  jTextFieldDayPhone.setBounds(130, 140, 120, 20);

  jButtonOk.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
  jButtonOk.setText("Ok");
  jPanel1.add(jButtonOk);
  jButtonOk.setBounds(60, 230, 80, 25);

  getContentPane().add(jPanel1);
  jPanel1.setBounds(0, 0, 370, 300);

  pack();
 }// </editor-fold>//GEN-END:initComponents

    /**
     * Returns jFileMenuItem 
     */
    public javax.swing.JMenuItem getFileMenuItem()
    {
        return jFileMenuItem;
    }



         /**
     * Returns an Itinerary domain object populated with user entered
     * data.
     */
    public Customer getSelectedData()
    {

        Customer customer = new Customer (   jTextFieldLastName.getText(),
                                             jTextFieldFirstName.getText(),
                                             jTextFieldEmail.getText(),
                                             jTextFieldPassword.getText(),
                                             jTextFieldDayPhone.getText(),
                                             jTextFieldEveningPhone.getText());
        return customer;
    }
 public javax.swing.JButton getOkButton()
 {
     return jButtonOk;
 }

  public javax.swing.JButton getCancelButton()
 {
     return jButtonCancel;
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterCustomerJFrame itineraryJFrame = new RegisterCustomerJFrame();
                
                //itineraryJFrame.setSize(350,300);                
                //itineraryJFrame.setVisible(true);                                
                //new ItineraryJFrame().setVisible(true);
            }
        });
    }
    
 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton jButtonCancel;
 private javax.swing.JButton jButtonOk;
 private javax.swing.JMenu jDataMenu;
 private javax.swing.JMenuItem jDatabaseMenuItem;
 private javax.swing.JMenu jFileMenu;
 private javax.swing.JMenuItem jFileMenuItem;
 private javax.swing.JLabel jLabelDropOffCity;
 private javax.swing.JLabel jLabelDropOffDate;
 private javax.swing.JLabel jLabelDropOffDateDay;
 private javax.swing.JLabel jLabelPickUpCity;
 private javax.swing.JLabel jLabelPickUpDate;
 private javax.swing.JLabel jLabelPickUpDateDay;
 private javax.swing.JMenuBar jMenuBar;
 private javax.swing.JPanel jPanel1;
 private javax.swing.JTextField jTextFieldDayPhone;
 private javax.swing.JTextField jTextFieldEmail;
 private javax.swing.JTextField jTextFieldEveningPhone;
 private javax.swing.JTextField jTextFieldFirstName;
 private javax.swing.JTextField jTextFieldLastName;
 private javax.swing.JTextField jTextFieldPassword;
 // End of variables declaration//GEN-END:variables
    
}
